site_name: SuperNOVA Wiki
docs_dir: ../docs
site_dir: ../../site
theme:
  name: 'readthedocs'
  custom_dir: 'theme'
  navigation_depth: 2
repo_url: https://github.com/S0L0GUY/SuperNOVA-Wiki
edit_uri: https://github.com/S0L0GUY/SuperNOVA-Wiki/edit/main
site_author: Evan Grinnell
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
plugins:
  - awesome-pages
exclude_docs: |
  !.images