site_name: SN Wiki
docs_dir: docs
site_dir: site
theme:
  name: 'readthedocs'
  custom_dir: '.github/theme'
  navigation_depth: 2
repo_url: https://github.com/s0l0guy/SuperNOVA-Wiki
edit_uri: https://github.com/s0l0guy/SuperNOVA-Wiki/edit/main/
site_author: Evan Grinnell
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
plugins:
  - awesome-pages
exclude_docs: |
  !.images